version: '2'

services:
  web:
    build: .
    ports:
      - 8000:80    
    volumes:
      - .:/var/www/html/

  db:
    image: mysql:5.6 
    environment:
      MYSQL_DATABASE: siuk
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - persistent:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 85:80

volumes:
  persistent:
